#!/bin/bash
# Install syntax color highlighting file if not already installed
SYNTAXDIR="$HOME/.vim/syntax"
SYNTAXFILE="vim-slides.vim"
TMPSLIDEDIR=$(mktemp -d -t vim-slides-XXXXXXXX)
SLIDEFILE="$1"

# Uninstall old syntax file if this is "newer" (i.e. different)
diff -q "$SYNTAXDIR/$SYNTAXFILE" "config.d/$SYNTAXFILE" > /dev/null
if [ $? -ne 0 ]; then
  rm "$SYNTAXDIR/$SYNTAXFILE"
fi

# Install syntax file when none is currently installed
if [ ! -f "$SYNTAXDIR/$SYNTAXFILE" ]; then
  mkdir -p $SYNTAXDIR
  cp config.d/$SYNTAXFILE $SYNTAXDIR
fi

if [ $# -ne 1 ]; then
  echo "USAGE: $0 <presentation file>"
  exit 1
fi

if [ ! -f "$SLIDEFILE" ]; then
  SLIDEFILE="slidedecks/$SLIDEFILE"
fi

if [ -f "$SLIDEFILE" ]; then
  SLIDEPREFIX=$TMPSLIDEDIR/$(basename $SLIDEFILE)
  split -p '^#-' "$SLIDEFILE" $SLIDEPREFIX.
  vim -u config.d/vim-slides.rc $SLIDEPREFIX.*
  rm -rf $TMPSLIDEDIR
fi
